#!/usr/bin/env python3
"""ClipBuilder -- MMA clip builder, analyzer, and montage generator."""

import os
import subprocess
import sys
import time
import webbrowser
from pathlib import Path


def _load_dotenv():
    """Load .env files into os.environ so subprocesses (gemini, codex, etc.)
    inherit keys like GEMINI_API_KEY regardless of which directory the app
    was launched from. Searches in this order, first match wins per key:

        1. <project_root>/.env         ← typical "I just dropped a .env here"
        2. <project_root>/.gemini/.env ← matches the gemini CLI's own lookup
        3. ~/.gemini/.env              ← user-home location

    Existing os.environ values are NOT overwritten so an explicit shell
    export still wins over a stale .env entry.
    """
    project_root = Path(__file__).parent.parent
    candidates = [
        project_root / ".env",
        project_root / ".gemini" / ".env",
        Path.home() / ".gemini" / ".env",
    ]
    for path in candidates:
        if not path.is_file():
            continue
        try:
            for line in path.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                if line.startswith("export "):
                    line = line[7:].lstrip()
                key, _, val = line.partition("=")
                key = key.strip()
                val = val.strip()
                # Strip surrounding single/double quotes if balanced.
                if (len(val) >= 2 and val[0] == val[-1]
                        and val[0] in ("'", '"')):
                    val = val[1:-1]
                if key and key not in os.environ:
                    os.environ[key] = val
        except Exception as exc:
            print(f"[env] Couldn't read {path}: {exc}")


_load_dotenv()


from flask import Flask, jsonify, redirect, send_file

from db import get_db
from clip_builder import clip_builder_bp
from analyzer import analyzer_bp
from folders import folders_bp
from crop_presets import crop_presets_bp

from library import library_bp
from wizard import wizard_bp
from rating import rating_bp
from settings_routes import settings_bp
import ai_badges
import app_config
import features

app = Flask(__name__)
app.register_blueprint(clip_builder_bp)
app.register_blueprint(analyzer_bp)
app.register_blueprint(folders_bp)
app.register_blueprint(crop_presets_bp)

app.register_blueprint(library_bp)
app.register_blueprint(wizard_bp)
app.register_blueprint(rating_bp)
app.register_blueprint(settings_bp)
if features.DRIVE_ENABLED:
    from drive_routes import drive_bp
    app.register_blueprint(drive_bp)

ROOT_DIR = Path(__file__).parent.parent

# Unique token per server process — changes on restart so the browser can detect it
_SERVER_ID = str(time.time())

_INJECTED_SCRIPT = """
<script>
window.PG_FEATURES = {drive: """ + ("true" if features.DRIVE_ENABLED else "false") + """};
window.PG_AI_BADGES = """ + ai_badges.badges_js_blob() + """;
// Global 2x multiplier on every badge — every call site's `size:` hint is
// doubled so changing the visual scale is a one-line tweak here.
window.PG_AI_BADGE_SCALE = 2;
window.pgAiBadge = function(provider, opts) {
  if (!provider || !window.PG_AI_BADGES[provider]) return '';
  var b = window.PG_AI_BADGES[provider];
  var base = (opts && opts.size) || 14;
  var size = base * (window.PG_AI_BADGE_SCALE || 1);
  // Always include the specific model in the hover tooltip when one is
  // available, so the visible brand badge can still surface "haiku vs
  // sonnet vs minimax-m1" on hover. opts.title (explicit) wins.
  var model = (opts && opts.model) || '';
  var title;
  if (opts && opts.title) {
    title = opts.title;
  } else {
    title = 'Generated by ' + b.label + (model ? ' · ' + model : '');
  }
  // Escape the title attribute so user-supplied model strings can't break
  // out of the surrounding quotes.
  var safe = String(title).replace(/&/g, '&amp;').replace(/"/g, '&quot;')
                           .replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return '<span class="pg-ai-badge" title="' + safe + '" data-model="'
    + String(model).replace(/&/g,'&amp;').replace(/"/g,'&quot;')
    + '" style="display:inline-flex;'
    + 'width:' + size + 'px;height:' + size + 'px;vertical-align:middle;'
    + 'flex-shrink:0;line-height:0;cursor:help;">' + b.svg + '</span>';
};
</script>
<style>.pg-ai-badge svg{width:100%;height:100%;display:block}</style>
<style>
/* -- Design System -- */
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap');

:root{
  --font-display:'Bebas Neue','Impact',sans-serif;
  --font-body:'Plus Jakarta Sans',-apple-system,BlinkMacSystemFont,sans-serif;
  --font-mono:'JetBrains Mono','SF Mono','Consolas',monospace;
  --bg-base:#08080c;
  --bg-surface:#111118;
  --bg-elevated:#1a1a24;
  --bg-hover:#22222e;
  --accent:#e53935;
  --accent-hover:#ff5252;
  --accent-glow:rgba(229,57,53,0.25);
  --accent-gold:#d4a017;
  --text-1:#eeeef2;
  --text-2:#8888a0;
  --text-3:#55556a;
  --border:#1e1e2a;
  --border-hover:#2e2e3e;
  --success:#22c55e;
  --error:#ef4444;
  --radius:10px;
  --radius-sm:6px;
  --radius-lg:16px;
}

body{
  background:var(--bg-base) !important;
  color:var(--text-1) !important;
  font-family:var(--font-body) !important;
  -webkit-font-smoothing:antialiased;
  -moz-osx-font-smoothing:grayscale;
}

::-webkit-scrollbar{width:6px;height:6px}
::-webkit-scrollbar-track{background:transparent}
::-webkit-scrollbar-thumb{background:var(--border-hover);border-radius:3px}
::-webkit-scrollbar-thumb:hover{background:#3a3a4e}

/* -- Sticky header -- */
header{
  position:sticky !important;top:0;z-index:50;
  display:flex !important;align-items:center !important;
  gap:16px !important;flex-wrap:nowrap !important;
  background:linear-gradient(180deg,#0e0e16 0%,#0b0b12 100%) !important;
  border-bottom:1px solid var(--border) !important;
  padding:14px 24px !important;
  backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);
}
header h1{
  font-family:var(--font-display) !important;
  font-size:26px !important;font-weight:400 !important;
  letter-spacing:3px !important;text-transform:uppercase !important;
  /* Match the Art Deco logo: warm brushed gold for the leading word
   * with a slight glow against the dark header bar. */
  color:#e6c068 !important;
  text-shadow:0 0 14px rgba(217,164,68,0.18) !important;
  white-space:nowrap !important;flex-shrink:0 !important;
}
/* Trailing word ("BUILDER") gets the deeper bronze tone from the logo's
 * shadowed strokes, so the two-tone split stays readable. */
header h1 span{color:#b08a3a !important}
nav{
  display:flex !important;gap:8px !important;
  margin-left:auto !important;flex-shrink:0 !important;
  align-items:center !important;
}
nav a{
  font-family:var(--font-body) !important;font-weight:600 !important;
  font-size:11px !important;letter-spacing:0.8px !important;
  text-transform:uppercase !important;
  padding:6px 14px !important;border-radius:var(--radius-sm) !important;
  border:1px solid var(--border) !important;color:var(--text-2) !important;
  text-decoration:none !important;transition:all 0.2s ease !important;
}
nav a:hover{
  color:var(--text-1) !important;border-color:var(--border-hover) !important;
  background:var(--bg-hover) !important;
}
nav a.active{
  color:var(--accent) !important;border-color:var(--accent) !important;
  background:rgba(229,57,53,0.08) !important;
  box-shadow:0 0 12px rgba(229,57,53,0.1) !important;
}

/* -- Global overrides -- */
button{
  font-family:var(--font-body) !important;font-weight:600 !important;
  letter-spacing:0.3px !important;transition:all 0.2s ease !important;
  border-radius:var(--radius-sm) !important;
}
button.primary,.btn-primary{
  background:linear-gradient(135deg,#e53935 0%,#c62828 100%) !important;
  box-shadow:0 2px 12px rgba(229,57,53,0.25) !important;
  border-color:#e53935 !important;
}
button.primary:hover,.btn-primary:hover{
  background:linear-gradient(135deg,#ff5252 0%,#e53935 100%) !important;
  box-shadow:0 4px 20px rgba(229,57,53,0.35) !important;
  transform:translateY(-1px);
}
input,select,textarea{
  font-family:var(--font-body) !important;
  transition:border-color 0.2s ease,box-shadow 0.2s ease !important;
}
input:focus,select:focus,textarea:focus{
  border-color:var(--accent) !important;
  box-shadow:0 0 0 2px var(--accent-glow) !important;
  outline:none !important;
}
th{
  font-family:var(--font-body) !important;font-size:10px !important;
  font-weight:700 !important;letter-spacing:1.2px !important;
  text-transform:uppercase !important;color:var(--text-3) !important;
}
@keyframes pgFadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}
main,.content,table{animation:pgFadeIn 0.35s ease-out}

/* -- Header logo -- */
/* The Art Deco PNG already renders in its intended dark + gold palette,
 * so no `invert` filter. We bump height 1.25× (28 → 35) and trim the
 * surrounding header padding to keep the bar at the same total height
 * (10 + 28 + 10 = 48  →  6 + 35 + 7 = 48). */
.header-logo{
  height:35px;width:auto;flex-shrink:0;
  margin-right:6px;border-radius:6px;
  display:block;
}
header{padding:6px 20px 7px}

/* -- Update button -- */
.update-btn{
  background:none;color:var(--text-3);border:1px solid var(--border);border-radius:var(--radius-sm);
  padding:4px 10px;font-size:10px;cursor:pointer;margin-left:8px;
  transition:all .2s;letter-spacing:0.5px;text-transform:uppercase;
}
.update-btn:hover{color:var(--accent);border-color:var(--accent)}
.update-btn.checking{color:var(--text-3);border-color:var(--border);cursor:wait}
.update-btn.updated{color:var(--success);border-color:var(--success)}
.update-btn.error{color:var(--error);border-color:var(--error)}

/* -- Global footer log -- */
#pg-footer{
  position:fixed;bottom:0;left:0;right:0;z-index:90;
  background:linear-gradient(180deg,#0c0c14 0%,#08080e 100%);
  border-top:1px solid var(--border);
  font-family:var(--font-body);
  backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);
}
#pg-footer-bar{
  display:flex;align-items:center;padding:5px 20px;cursor:pointer;
  user-select:none;gap:10px;
}
#pg-footer-bar:hover{background:rgba(255,255,255,0.02)}
#pg-footer-bar .ft-label{font-size:10px;color:var(--text-3);font-weight:700;letter-spacing:1.5px;text-transform:uppercase}
#pg-footer-bar .ft-count{
  font-size:10px;color:var(--text-3);background:var(--bg-elevated);border-radius:8px;padding:1px 7px;font-weight:600;
}
#pg-footer-bar .ft-last{
  font-size:11px;color:var(--text-3);flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;
}
#pg-footer-bar .ft-arrow{color:var(--text-3);font-size:10px;transition:transform .2s}
#pg-footer-bar .ft-arrow.open{transform:rotate(180deg)}
#pg-footer-bar .ft-clear{
  background:none;border:1px solid var(--border);color:var(--text-3);border-radius:4px;
  padding:1px 7px;font-size:10px;cursor:pointer;
}
#pg-footer-bar .ft-clear:hover{color:var(--accent);border-color:var(--accent)}
#pg-log-panel{
  display:none;max-height:200px;overflow-y:auto;padding:6px 20px 8px;
  border-top:1px solid var(--border);
}
#pg-log-panel.open{display:block}
#pg-log-panel .lg{font-size:11px;padding:2px 0;color:var(--text-2);font-family:var(--font-mono)}
#pg-log-panel .lg .lg-time{color:var(--text-3);margin-right:8px}
#pg-log-panel .lg.lg-error{color:var(--error)}
#pg-log-panel .lg.lg-ok{color:var(--success)}
</style>

<div id="pg-footer">
  <div id="pg-footer-bar" onclick="window._pgToggleLog()">
    <span class="ft-label">LOG</span>
    <span class="ft-count" id="pg-log-count">0</span>
    <span class="ft-last" id="pg-log-last"></span>
    <button class="ft-clear" onclick="event.stopPropagation();window._pgClearLog()">Clear</button>
    <span class="ft-arrow" id="pg-log-arrow">&#9650;</span>
  </div>
  <div id="pg-log-panel"></div>
</div>

<script>
(function(){
  /* ── Live reload ── */
  var sid='""" + _SERVER_ID + """';
  setInterval(function(){
    fetch('/api/server-id').then(function(r){return r.json()}).then(function(d){
      if(d.id!==sid){location.reload()}
    }).catch(function(){});
  },1500);

  /* ── Header: inject logo (clickable → About modal) ── */
  var h1 = document.querySelector('header h1');
  if (h1 && !document.querySelector('.header-logo')) {
    var logo = document.createElement('img');
    logo.src = '/api/logo';
    logo.alt = 'ClipBuilder';
    logo.className = 'header-logo';
    logo.style.cursor = 'pointer';
    logo.title = 'About ClipBuilder';
    logo.addEventListener('click', function(){ window._pgOpenAbout(); });
    h1.parentNode.insertBefore(logo, h1);
    // Also make the title text clickable so users hit either.
    h1.style.cursor = 'pointer';
    h1.addEventListener('click', function(){ window._pgOpenAbout(); });
  }

  /* ── Header: inject active-brand pill ── */
  var headerEl = document.querySelector('header');
  if (headerEl && window.PG_APP && window.PG_APP.brand
      && !headerEl.querySelector('.pg-brand-pill')) {
    // Resolve the per-profile color (set by the Settings Wizard from the
    // brand's website) and derive bg / border / hover / fg from it. Falls
    // back to the default purple when the profile has no brand_color set.
    function _pgHexToRgba(hex, alpha) {
      var h = (hex || '').replace(/^#/, '');
      if (h.length === 3) h = h.split('').map(function(c){return c+c}).join('');
      if (!/^[0-9a-fA-F]{6}$/.test(h)) h = '7c3aed';
      var r = parseInt(h.slice(0,2),16),
          g = parseInt(h.slice(2,4),16),
          b = parseInt(h.slice(4,6),16);
      return 'rgba(' + r + ',' + g + ',' + b + ',' + alpha + ')';
    }
    function _pgReadableFg(hex) {
      // Mix toward white 55% so the label stays bright but keeps the
      // brand hue. Matches the picker's preview swatch.
      var h = (hex || '').replace(/^#/, '');
      if (h.length === 3) h = h.split('').map(function(c){return c+c}).join('');
      if (!/^[0-9a-fA-F]{6}$/.test(h)) h = '7c3aed';
      var r = parseInt(h.slice(0,2),16),
          g = parseInt(h.slice(2,4),16),
          b = parseInt(h.slice(4,6),16);
      function mix(c){ return Math.round(c + (255 - c) * 0.55); }
      return 'rgb(' + mix(r) + ',' + mix(g) + ',' + mix(b) + ')';
    }
    var brandHex = window.PG_APP.brand_color || '#7c3aed';
    var pill = document.createElement('a');
    pill.href = '/settings';
    pill.className = 'pg-brand-pill';
    pill.title = 'Active brand profile — click to switch';
    pill.textContent = window.PG_APP.brand;
    pill.style.cssText = ''
      + 'display:inline-flex;align-items:center;gap:5px;'
      + 'padding:4px 10px;border-radius:99px;'
      + 'background:' + _pgHexToRgba(brandHex, 0.15) + ';'
      + 'color:' + _pgReadableFg(brandHex) + ';'
      + 'border:1px solid ' + _pgHexToRgba(brandHex, 0.4) + ';'
      + 'font-size:10px;font-weight:700;letter-spacing:0.5px;'
      + 'text-transform:uppercase;text-decoration:none;'
      + 'margin-left:12px;cursor:pointer;flex-shrink:0;'
      + 'transition:background .2s;';
    pill.onmouseenter = function(){ this.style.background = _pgHexToRgba(brandHex, 0.28); };
    pill.onmouseleave = function(){ this.style.background = _pgHexToRgba(brandHex, 0.15); };
    var nav0 = headerEl.querySelector('nav');
    if (nav0) headerEl.insertBefore(pill, nav0);
    else headerEl.appendChild(pill);
  }

  /* ── Header: inject Rate badge + Update button ── */
  var nav = document.querySelector('header nav');
  if (nav) {
    var scenesLink = nav.querySelector('a[href="/rate"]');
    if (scenesLink) {
      scenesLink.style.position = 'relative';
      fetch('/rate/api/scenes').then(function(r){return r.json()}).then(function(data){
        var unrated = data.filter(function(s){return !s.excluded && s.status==='unrated'}).length;
        if (unrated > 0) {
          var badge = document.createElement('span');
          badge.style.cssText = 'position:absolute;top:-6px;right:-6px;background:var(--accent,#e53935);color:#fff;font-size:8px;font-weight:800;min-width:16px;height:16px;border-radius:8px;display:flex;align-items:center;justify-content:center;padding:0 4px;';
          badge.textContent = unrated;
          scenesLink.appendChild(badge);
        }
      });
    }
    if (window.PG_FEATURES && window.PG_FEATURES.drive
        && !nav.querySelector('a[href="/drive"]')) {
      var driveLink = document.createElement('a');
      driveLink.href = '/drive';
      driveLink.textContent = 'Drive';
      if (location.pathname === '/drive') driveLink.className = 'active';
      nav.appendChild(driveLink);
    }
    if (!nav.querySelector('a[href="/settings"]')) {
      var settingsLink = document.createElement('a');
      settingsLink.href = '/settings';
      settingsLink.textContent = 'Settings';
      if (location.pathname === '/settings') settingsLink.className = 'active';
      nav.appendChild(settingsLink);
    }
    /* "Check for Updates" lives inside the About modal now (opened by
     * clicking the header logo). Keeps the nav clean and groups the
     * version info with the action that bumps it. */
  }

  /* ── About-the-app modal ── */
  function _buildAboutModal() {
    if (document.getElementById('pg-about-overlay')) return;
    var ov = document.createElement('div');
    ov.id = 'pg-about-overlay';
    ov.style.cssText = ''
      + 'display:none;position:fixed;inset:0;z-index:99000;'
      + 'background:rgba(0,0,0,.78);align-items:center;justify-content:center;'
      + 'padding:20px;box-sizing:border-box;';
    ov.addEventListener('click', function(e){ if (e.target === ov) _pgCloseAbout(); });
    ov.innerHTML = ''
      + '<div id="pg-about-modal" style="'
      +   'background:#15151c;border:1px solid #2e2e3e;border-radius:14px;'
      +   'width:min(440px,100%);padding:24px;box-sizing:border-box;'
      +   'box-shadow:0 20px 60px rgba(0,0,0,.7);text-align:center;'
      + '">'
      +   '<button onclick="window._pgCloseAbout()" '
      +     'style="position:absolute;top:14px;right:18px;background:none;'
      +     'border:none;color:#888;font-size:22px;cursor:pointer;'
      +     'line-height:1;padding:0">&times;</button>'
      +   '<img src="/api/logo" alt="ClipBuilder" '
      +     'style="width:180px;height:auto;display:block;margin:0 auto 14px;'
      +     'border-radius:14px;background:#0a0a0a">'
      +   '<div style="font-size:20px;font-weight:700;color:#fff;'
      +     'letter-spacing:0.5px;margin-bottom:4px">ClipBuilder</div>'
      +   '<div id="pg-about-version" style="font-size:13px;color:#888;'
      +     'font-family:\\'SF Mono\\',Menlo,monospace;margin-bottom:4px">'
      +     'Loading version…</div>'
      +   '<div id="pg-about-modified" style="font-size:11px;color:#555;'
      +     'margin-bottom:18px">&nbsp;</div>'
      +   '<button id="pg-update-btn" class="update-btn" '
      +     'style="margin:0 auto">Check for Updates</button>'
      +   '<div id="pg-update-status" style="font-size:11px;color:#888;'
      +     'margin-top:10px;min-height:14px">&nbsp;</div>'
      + '</div>';
    // Place the close button relative to the modal box.
    document.body.appendChild(ov);
    var modal = ov.querySelector('#pg-about-modal');
    modal.style.position = 'relative';

    var updBtn = ov.querySelector('#pg-update-btn');
    var updStatus = ov.querySelector('#pg-update-status');
    updBtn.addEventListener('click', async function(){
      updBtn.className = 'update-btn checking';
      updBtn.textContent = 'Checking…';
      updBtn.disabled = true;
      updStatus.textContent = '';
      try {
        var res = await fetch('/api/update', {method:'POST'});
        var data = await res.json();
        if (data.status === 'updated') {
          updBtn.className = 'update-btn updated';
          updBtn.textContent = 'Updated — restarting…';
          updStatus.textContent = (data.message || '');
        } else if (data.status === 'up-to-date') {
          updBtn.className = 'update-btn updated';
          updBtn.textContent = 'Up to date';
          updStatus.textContent = 'No changes pulled from origin.';
          setTimeout(_resetUpdateBtn, 3000);
        } else {
          updBtn.className = 'update-btn error';
          updBtn.textContent = 'Update failed';
          updStatus.textContent = data.message || '';
          setTimeout(_resetUpdateBtn, 4000);
        }
      } catch (e) {
        updBtn.className = 'update-btn error';
        updBtn.textContent = 'Error';
        updStatus.textContent = e.message || '';
        setTimeout(_resetUpdateBtn, 3000);
      }
    });
    function _resetUpdateBtn(){
      updBtn.className = 'update-btn';
      updBtn.textContent = 'Check for Updates';
      updBtn.disabled = false;
    }
  }

  window._pgOpenAbout = function() {
    _buildAboutModal();
    var ov = document.getElementById('pg-about-overlay');
    ov.style.display = 'flex';
    // Re-fetch build info every open so the version reflects any new
    // commit / file save without needing a page reload.
    fetch('/api/build-info').then(function(r){return r.json()}).then(function(b){
      var ver = 'v' + (b.version || '0.0.0');
      if (b.sha)   ver += ' · ' + b.sha;
      if (b.dirty) ver += ' (dev)';
      var vEl = document.getElementById('pg-about-version');
      if (vEl) vEl.textContent = ver;
      var mEl = document.getElementById('pg-about-modified');
      if (mEl) mEl.textContent = b.modified
        ? 'Built ' + b.modified : '';
    }).catch(function(){});
  };
  window._pgCloseAbout = function() {
    var ov = document.getElementById('pg-about-overlay');
    if (ov) ov.style.display = 'none';
  };
  document.addEventListener('keydown', function(e){
    if (e.key === 'Escape') {
      var ov = document.getElementById('pg-about-overlay');
      if (ov && ov.style.display === 'flex') window._pgCloseAbout();
    }
  });

  /* ── Global footer log ── */
  var logCount = 0;
  var panel = document.getElementById('pg-log-panel');
  var countEl = document.getElementById('pg-log-count');
  var lastEl = document.getElementById('pg-log-last');
  var arrowEl = document.getElementById('pg-log-arrow');

  window.pgLog = function(msg, cls) {
    if (!msg || typeof msg !== 'string') return;
    msg = msg.trim();
    if (!msg || msg === 'waiting...') return;
    logCount++;
    countEl.textContent = logCount;
    lastEl.textContent = msg;

    var div = document.createElement('div');
    div.className = 'lg' + (cls ? ' lg-' + cls : '');
    var now = new Date();
    var ts = now.getHours().toString().padStart(2,'0') + ':'
           + now.getMinutes().toString().padStart(2,'0') + ':'
           + now.getSeconds().toString().padStart(2,'0');
    div.innerHTML = '<span class="lg-time">' + ts + '</span>' + msg.replace(/</g,'&lt;');
    panel.appendChild(div);
    panel.scrollTop = panel.scrollHeight;
  };

  window._pgToggleLog = function() {
    panel.classList.toggle('open');
    arrowEl.classList.toggle('open');
  };

  window._pgClearLog = function() {
    panel.innerHTML = '';
    logCount = 0;
    countEl.textContent = '0';
    lastEl.textContent = '';
  };

  /* Hook into existing addLine functions to feed the global log */
  var _origAddLine = window.addLine;
  if (typeof _origAddLine === 'function') {
    window.addLine = function(text, cls) {
      _origAddLine(text, cls);
      var logCls = (cls === 'done' || cls === 'video-ready') ? 'ok' : (cls === 'error' ? 'error' : '');
      window.pgLog(text, logCls);
    };
  }

  /* Also hook addPipelineLine if it exists */
  var _origPipeLine = window.addPipelineLine;
  if (typeof _origPipeLine === 'function') {
    window.addPipelineLine = function(text, cls) {
      _origPipeLine(text, cls);
      var logCls = (cls === 'done') ? 'ok' : (cls === 'error' ? 'error' : '');
      window.pgLog(text, logCls);
    };
  }

  /* Log page load */
  window.pgLog('Page loaded: ' + location.pathname);

  /* Patch EventSource to log SSE messages to the footer */
  var _OrigES = window.EventSource;
  if (_OrigES) {
    window.EventSource = function(url) {
      var es = new _OrigES(url);
      es.addEventListener('message', function(e) {
        try {
          var data = JSON.parse(e.data);
          if (data.message) {
            var msg = data.message;
            var cls = '';
            if (msg.startsWith('DONE:')) cls = msg === 'DONE:ok' ? 'ok' : 'error';
            window.pgLog(msg, cls);
          }
        } catch(ex) {}
      });
      return es;
    };
    window.EventSource.prototype = _OrigES.prototype;
    window.EventSource.CONNECTING = _OrigES.CONNECTING;
    window.EventSource.OPEN = _OrigES.OPEN;
    window.EventSource.CLOSED = _OrigES.CLOSED;
  }
})();
</script>
<style>
.nav-badge{
  display:inline-flex;align-items:center;justify-content:center;
  min-width:16px;height:16px;padding:0 4px;
  background:#e53935;color:#fff;font-size:10px;font-weight:700;
  border-radius:8px;margin-left:4px;vertical-align:middle;
  animation:badge-pulse 2s ease-in-out infinite;
}
@keyframes badge-pulse{0%,100%{opacity:1}50%{opacity:.6}}
</style>
<script>
(function(){
  var analyzeLink = document.querySelector('nav a[href="/analyze"]');
  if (!analyzeLink) return;
  var badge = null;
  function updateBadge() {
    fetch('/api/unanalyzed-count').then(function(r){return r.json()}).then(function(d) {
      var c = d.count || 0;
      if (c > 0) {
        if (!badge) {
          badge = document.createElement('span');
          badge.className = 'nav-badge';
          analyzeLink.appendChild(badge);
        }
        badge.textContent = c;
      } else if (badge) {
        badge.remove();
        badge = null;
      }
    }).catch(function(){});
  }
  updateBadge();
  setInterval(updateBadge, 15000);
})();
</script>
"""


@app.route("/")
def index():
    return redirect("/builder")


@app.route("/api/server-id")
def server_id():
    """Returns a token that changes when the server restarts."""
    return jsonify({"id": _SERVER_ID})


@app.route("/api/logo")
def logo():
    """Serve the logo image. Prefers the high-res PNG under
    ``assets/images/`` and falls back to the legacy ``logo.jpeg`` for
    environments that haven't been updated yet."""
    candidates = [
        (ROOT_DIR / "assets" / "images" / "Clip Builder Logo.png", "image/png"),
        (ROOT_DIR / "assets" / "logo.jpeg", "image/jpeg"),
    ]
    for path, mime in candidates:
        if path.exists():
            return send_file(str(path), mimetype=mime)
    return "", 404


def _compute_build_info():
    """Return a dict describing the current build: a numeric version
    derived from the git commit count, the short SHA, a "dirty" flag if
    the working tree has uncommitted changes, and the timestamp of the
    most recently modified ``.py`` file (so dirty builds also visibly
    advance after every code change without needing a commit)."""
    info = {"version": "0.0.0", "sha": "", "dirty": False, "modified": ""}
    try:
        count = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            capture_output=True, text=True, cwd=str(ROOT_DIR), timeout=4,
        ).stdout.strip()
        sha = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=str(ROOT_DIR), timeout=4,
        ).stdout.strip()
        # `git status --porcelain` lists changed paths; non-empty → dirty.
        dirty = bool(subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, cwd=str(ROOT_DIR), timeout=4,
        ).stdout.strip())
        if count.isdigit():
            n = int(count)
            # Semver-ish: every 100 commits bumps the minor.
            major, rem = divmod(n, 10000)
            minor, patch = divmod(rem, 100)
            info["version"] = f"{major}.{minor}.{patch}"
        info["sha"] = sha
        info["dirty"] = dirty
    except Exception:
        pass
    # Track the most-recent .py mtime — dirty edits without a commit
    # still advance this so the modal shows the user that their change
    # is reflected in the running server.
    try:
        latest = 0.0
        for p in (ROOT_DIR / "src").glob("*.py"):
            try:
                latest = max(latest, p.stat().st_mtime)
            except OSError:
                pass
        if latest:
            from datetime import datetime as _dt
            info["modified"] = _dt.fromtimestamp(latest).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        pass
    return info


@app.route("/api/build-info")
def build_info():
    """Build metadata for the About-the-app modal in the header logo."""
    return jsonify(_compute_build_info())


REPO_HTTPS = "https://github.com/paxlucta/peace-grappler.git"


@app.route("/api/update", methods=["POST"])
def check_for_updates():
    """Pull latest code from git. Werkzeug reloader restarts if .py files changed."""
    try:
        # Find the git repo root (may be parent of pg-clip-builder)
        git_root = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, cwd=str(ROOT_DIR), timeout=10,
        ).stdout.strip()

        if not git_root:
            # Not a git repo — bootstrap one so updates work going forward
            git_root = str(ROOT_DIR.parent)  # peace-grappler/ level
            subprocess.run(
                ["git", "init"], cwd=git_root,
                capture_output=True, timeout=10,
            )
            subprocess.run(
                ["git", "remote", "add", "origin", REPO_HTTPS],
                cwd=git_root, capture_output=True, timeout=10,
            )
            subprocess.run(
                ["git", "fetch", "origin"],
                cwd=git_root, capture_output=True, timeout=30,
            )
            # Set the current state as tracking main
            subprocess.run(
                ["git", "checkout", "-b", "main"],
                cwd=git_root, capture_output=True, timeout=10,
            )
            subprocess.run(
                ["git", "branch", "--set-upstream-to=origin/main", "main"],
                cwd=git_root, capture_output=True, timeout=10,
            )
            # Reset to match remote (picks up latest code)
            result = subprocess.run(
                ["git", "reset", "--hard", "origin/main"],
                cwd=git_root, capture_output=True, text=True, timeout=30,
            )
            if result.returncode != 0:
                return jsonify({"status": "error",
                                "message": "Bootstrap failed: " + result.stderr.strip()})
            return jsonify({"status": "updated", "from": "initial", "to": "latest"})

        # Ensure remote uses HTTPS (SSH won't work without keys)
        cur_remote = subprocess.run(
            ["git", "config", "--get", "remote.origin.url"],
            capture_output=True, text=True, cwd=git_root, timeout=10,
        ).stdout.strip()
        if cur_remote.startswith("git@"):
            subprocess.run(
                ["git", "remote", "set-url", "origin", REPO_HTTPS],
                cwd=git_root, capture_output=True, timeout=10,
            )

        # Fetch latest
        fetch = subprocess.run(
            ["git", "fetch", "origin"],
            capture_output=True, text=True, cwd=git_root, timeout=30,
        )
        if fetch.returncode != 0:
            return jsonify({"status": "error",
                            "message": "Fetch failed: " + fetch.stderr.strip()})

        # Check if there are updates
        local = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True, cwd=git_root, timeout=10,
        ).stdout.strip()

        remote = subprocess.run(
            ["git", "rev-parse", "@{u}"],
            capture_output=True, text=True, cwd=git_root, timeout=10,
        ).stdout.strip()

        if local == remote:
            return jsonify({"status": "up-to-date"})

        # Pull (reset to match remote — safe because user code is in videos/assets/output)
        result = subprocess.run(
            ["git", "reset", "--hard", "@{u}"],
            capture_output=True, text=True, cwd=git_root, timeout=30,
        )

        if result.returncode != 0:
            return jsonify({"status": "error",
                            "message": "Pull failed: " + result.stderr.strip()})

        # Reinstall deps in case requirements.txt changed
        venv_pip = ROOT_DIR / ".venv" / "bin" / "pip"
        req_file = ROOT_DIR / "requirements.txt"
        if venv_pip.exists() and req_file.exists():
            subprocess.Popen(
                [str(venv_pip), "install", "-q", "-r", str(req_file)],
                cwd=str(ROOT_DIR),
            )

        return jsonify({"status": "updated",
                        "from": local[:8], "to": remote[:8]})

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)})


@app.route("/api/unanalyzed-count")
def unanalyzed_count():
    """Return count of videos that haven't been analyzed yet."""
    from db import get_all_videos, get_analyzed_tags
    try:
        videos = get_all_videos()
        count = sum(1 for v in videos if not get_analyzed_tags(v["id"]) and v["duration"] > 0)
        return jsonify({"count": count})
    except Exception:
        return jsonify({"count": 0})


@app.after_request
def inject_scripts(response):
    """Inject live-reload, AI badges, and current app brand into HTML responses."""
    if (response.content_type
            and "text/html" in response.content_type):
        import json as _json
        # Read fresh every request — brand / handle / domain edits take
        # effect without a restart. domain_vars derives {handle} from the
        # Social Channels block (IG → TikTok → YouTube fallback).
        brand_blob = (
            "<script>window.PG_APP = "
            + _json.dumps(app_config.domain_vars())
            + ";</script>"
        )
        data = response.get_data(as_text=True)
        data = data.replace("</body>",
                            brand_blob + _INJECTED_SCRIPT + "</body>")
        response.set_data(data)
    return response


def _start_video_watcher():
    """Background thread that watches the active profile's source folder
    for new files, registers them, and auto-analyzes unanalyzed videos.

    The source folder is re-resolved from app_config every tick so a profile
    switch in /settings is honored without a restart. Each profile keeps a
    private set of "known files" so switching back doesn't re-register
    everything as new.
    """
    import threading
    from video import VIDEO_EXTENSIONS
    from db import register_video, get_all_videos, get_analyzed_tags

    SCAN_INTERVAL = 30  # seconds between local scans
    DRIVE_PULL_INTERVAL = 300  # seconds between Drive pulls (every 5 minutes)
    _known_files_by_profile = {}   # profile_name -> set[str path]
    _last_drive_pull = [0.0]       # mutable so the inner func can update it

    def _current_paths():
        """Return (active_profile_name, source_path) freshly resolved."""
        import app_config
        return (
            app_config.get_active_profile_name(),
            app_config.get_source_dir(),
        )

    def _maybe_pull_drive(video_dir):
        """Pull from the Drive inbox folder if connected and configured."""
        if not features.DRIVE_ENABLED:
            return
        import time as _t
        if _t.time() - _last_drive_pull[0] < DRIVE_PULL_INTERVAL:
            return
        try:
            import drive
            from db import register_video as _rv
            from db import get_video_by_drive_file_id, set_video_drive_info
            cfg = drive.get_config()
            if not (cfg["app_configured"] and cfg["has_token"]
                    and cfg["inbox_folder_id"]):
                return
            _last_drive_pull[0] = _t.time()
            items = drive.list_inbox_videos()
            existing_local = {p.name for p in video_dir.iterdir() if p.is_file()}
            for it in items:
                fid, name = it["id"], it["name"]
                if get_video_by_drive_file_id(fid) or name in existing_local:
                    continue
                dest = video_dir / name
                print(f"[watcher] Drive pull: downloading {name}...")
                try:
                    drive.download_file(fid, dest)
                    vid_id = _rv(dest)
                    set_video_drive_info(
                        vid_id, fid,
                        f"https://drive.google.com/file/d/{fid}/view",
                    )
                    print(f"[watcher] Drive pull: registered {name}")
                except Exception as exc:
                    print(f"[watcher] Drive pull failed for {name}: {exc}")
        except Exception as exc:
            print(f"[watcher] Drive pull error: {exc}")

    def _scan_and_analyze():
        profile, video_dir = _current_paths()
        _maybe_pull_drive(video_dir)
        video_dir.mkdir(parents=True, exist_ok=True)
        known = _known_files_by_profile.setdefault(profile, set())
        current_files = set()
        for root, _, files in os.walk(video_dir):
            for name in sorted(files):
                if Path(name).suffix.lower() in VIDEO_EXTENSIONS and not name.startswith("."):
                    current_files.add(str(Path(root) / name))

        new_files = current_files - known
        known.update(current_files)

        if new_files:
            print(f"[watcher] Found {len(new_files)} new video(s), registering...")
            for fpath in sorted(new_files):
                try:
                    register_video(fpath)
                    print(f"[watcher] Registered: {Path(fpath).name}")
                except Exception as exc:
                    print(f"[watcher] Failed to register {fpath}: {exc}")

        # Auto-analyze unanalyzed videos
        try:
            from analyzer import analyze_full, save_analysis, ALL_TAG_SET, get_analyzed_tags as get_at
            videos = get_all_videos()
            for v in videos:
                analyzed_tags = get_at(v["id"])
                if not analyzed_tags and v["duration"] > 0:
                    print(f"[watcher] Auto-analyzing: {v['filename']}...")
                    try:
                        result = analyze_full(v["path"], v["duration"])
                        if result:
                            save_analysis(v["id"], result["tags"],
                                          result["moments"], list(ALL_TAG_SET))
                            print(f"[watcher] Analyzed {v['filename']}: {len(result['tags'])} tags")
                        else:
                            print(f"[watcher] Analysis returned no results for {v['filename']}")
                    except Exception as exc:
                        print(f"[watcher] Analysis failed for {v['filename']}: {exc}")
        except Exception as exc:
            print(f"[watcher] Auto-analyze error: {exc}")

    def _watcher_loop():
        # Initial scan: seed the known-files set for the active profile so
        # we don't re-register pre-existing videos as "new".
        profile, video_dir = _current_paths()
        video_dir.mkdir(parents=True, exist_ok=True)
        known = _known_files_by_profile.setdefault(profile, set())
        for root, _, files in os.walk(video_dir):
            for name in sorted(files):
                if (Path(name).suffix.lower() in VIDEO_EXTENSIONS
                        and not name.startswith(".")):
                    known.add(str(Path(root) / name))
        print(f"[watcher] Watching {video_dir} for profile '{profile}' "
              f"({len(known)} existing videos)")

        import time as _time
        while True:
            _time.sleep(SCAN_INTERVAL)
            try:
                _scan_and_analyze()
            except Exception as exc:
                print(f"[watcher] Error: {exc}")

    t = threading.Thread(target=_watcher_loop, daemon=True)
    t.start()


def _wait_for_port_free(port, timeout=15.0):
    """Poll until *port* is bindable on 0.0.0.0 or *timeout* elapses.

    Used when this process was spawned by ``/settings/api/restart`` —
    the old instance is still alive and holding the port until its
    SIGTERM lands. We try a throwaway bind every 300 ms so app.run()
    only gets called once the kernel has released the address.
    """
    import socket as _sock
    import time as _t
    deadline = _t.time() + max(0.5, float(timeout))
    while _t.time() < deadline:
        s = _sock.socket(_sock.AF_INET, _sock.SOCK_STREAM)
        try:
            s.setsockopt(_sock.SOL_SOCKET, _sock.SO_REUSEADDR, 1)
            s.bind(("0.0.0.0", port))
            s.close()
            return True
        except OSError:
            try: s.close()
            except Exception: pass
            _t.sleep(0.3)
    return False


def main():
    port = 5555
    if "--port" in sys.argv:
        idx = sys.argv.index("--port")
        if idx + 1 < len(sys.argv):
            port = int(sys.argv[idx + 1])

    # When the previous process spawned us via the Settings restart
    # endpoint, the parent is still alive holding the port until its
    # SIGTERM lands. Poll until the port is bindable before continuing
    # so Werkzeug doesn't blow up with EADDRINUSE on startup.
    if "--wait-bind" in sys.argv:
        print(f"[restart] Waiting for port {port} to free up…")
        _wait_for_port_free(port, timeout=15.0)

    # Initialize DB
    get_db()

    use_reloader = "--no-reload" not in sys.argv
    debug = use_reloader

    # Start background video watcher (only in the main process, not reloader child)
    if os.environ.get("WERKZEUG_RUN_MAIN") or not use_reloader:
        _start_video_watcher()

    # Only open browser on first launch, not on reloader restarts
    if not os.environ.get("WERKZEUG_RUN_MAIN"):
        print(f"Starting ClipBuilder at http://localhost:{port}")
        if use_reloader:
            print("Auto-reload enabled — watching for file changes")
            webbrowser.open(f"http://localhost:{port}")

    app.run(host="0.0.0.0", port=port, debug=debug,
            use_reloader=use_reloader)


if __name__ == "__main__":
    main()
